from datetime import date

STORMS = {
    "BODIL": { #Hurricane
        "BaseDir": "StormBodil",
        "AffectedFolder": "affected",
        "NotAffectedFolder": "notAffected",
        "AFFECTED": {
            "0550": "SBOTønder.csv",
            "0665": "SBOLemvig.csv",
            "0787": "SBOThisted.csv",
            "0860": "SBOHjørring.csv",
            "0849": "SBOJammerbugt.csv",
            "0326": "SBOKalundborg.csv",
            "0306": "SBOOdsherred.csv",
            "0760": "SBORingkøbingSkjern.csv",
            "0561": "SBOEsbjerg.csv",
            "0563": "SBOFanø.csv"
        },
        "NOT_AFFECTED": {
            "0329": "SBORingsted.csv",
            "0370": "SBONæstved.csv",
            "0657": "SBOHerning.csv",
            "0530": "SBOBillund.csv",
            "0710": "SBOFavrskov.csv",
            "0791": "SBOViborg.csv",
            "0840": "SBORebild.csv",
            "0846": "SBOMariagerfjord.csv",
            "0730": "SBORanders.csv",
            "0851": "SBOAalborg.csv"
        },
        "StartDate": date(2012, 12, 4),
        "EndDate": date(2013, 12, 4),
    },
    "EGON": { #Storm
        "BaseDir": "StormEgon",
        "AffectedFolder": "affected",
        "NotAffectedFolder": "notAffected",
        "AFFECTED": {
            "0550": "SEGTønder.csv",
            "0665": "SEGLemvig.csv",
            "0787": "SEGThisted.csv",
            "0860": "SEGHjørring.csv",
            "0849": "SEGJammerbugt.csv",
            "0661": "SEGHolstebro.csv",
            "0671": "SEGStruer.csv",
            "0760": "SEGRingkøbingSkjern.csv",
            "0561": "SEGEsbjerg.csv",
            "0563": "SEGFanø.csv"
        },
        "NOT_AFFECTED": {
            "0461": "SEGOdense.csv", 
            "0370": "SEGNæstved.csv",
            "0340": "SEGSorø.csv",
            "0329": "SEGRingsted.csv",
            "0350": "SEGLejre.csv",
            "0840": "SEGRebild.csv",
            "0791": "SEGViborg.csv",
            "0710": "SEGFavrskov.csv",
            "0740": "SEGSilkeborg.csv",
            "0621": "SEGKolding.csv"
        },
        "StartDate": date(2014, 1, 9),
        "EndDate": date(2015, 1, 9),
    },
    "GORM": { #Strong storm (hurricane-like)
        "BaseDir": "StormGorm",
        "AffectedFolder": "affected",
        "NotAffectedFolder": "notAffected",
         "AFFECTED": {
            "0550": "SGOTønder.csv",
            "0665": "SGOLemvig.csv",
            "0707": "SGONorddjurs.csv", 
            "0657": "SGOHerning.csv", 
            "0573": "SGOVarde.csv", 
            "0326": "SGOKalundborg.csv",
            "0306": "SGOOdsherred.csv",
            "0760": "SGORingkøbingSkjern.csv",
            "0561": "SGOEsbjerg.csv", 
            "0563": "SGOFanø.csv"
        }, 
        "NOT_AFFECTED": {
            "0329": "SGORingsted.csv",
            "0370": "SGONæstved.csv",
            "0390": "SGOVordingborg.csv",
            "0479": "SGOSvendborg.csv", 
            "0820": "SGOVesthimmerland.csv",
            "0340": "SGOSorø.csv",
            "0851": "SGOAalborg.csv",
            "0787": "SGOThisted.csv",
            "0773": "SGOMorsø.csv",
            "0810": "SGOBrønderslev.csv"
        },
        "StartDate": date(2014, 11, 28),
        "EndDate": date(2015, 11, 28),
    },
    "URD": { #Storm
        "BaseDir": "StormUrd",
        "AffectedFolder": "affected",
        "NotAffectedFolder": "notAffected",
        "AFFECTED": {
            "0550": "SURTønder.csv",
            "0665": "SURLemvig.csv",
            "0787": "SURThisted.csv",
            "0860": "SURHjørring.csv",
            "0849": "SURJammerbugt.csv",
            "0326": "SURKalundborg.csv",
            "0306": "SUROdsherred.csv",
            "0760": "SURRingkøbingSkjern.csv",
            "0561": "SUREsbjerg.csv",
            "0563": "SURFanø.csv"
        }, 
        "NOT_AFFECTED": {
            "0329": "SURRingsted.csv",
            "0370": "SURNæstved.csv",
            "0657": "SURHerning.csv",
            "0530": "SURBillund.csv",
            "0575": "SURVejen.csv",
            "0340": "SURSorø.csv",
            "0461": "SUROdense.csv",
            "0420": "SURAssens.csv",
            "0621": "SURKolding.csv",
            "0630": "SURVejle.csv"
        },
        "StartDate": date(2015, 12, 25),
        "EndDate": date(2016, 12, 25),
    },
    "MALIK": { #Storm
        "BaseDir": "StormMalik",
        "AffectedFolder": "affected",
        "NotAffectedFolder": "notAffected",
        "AFFECTED": {
            "0671": "SMAStruer.csv", 
            "0665": "SMALemvig.csv",
            "0787": "SMAThisted.csv",
            "0860": "SMAHjørring.csv",
            "0849": "SMAJammerbugt.csv",
            "0326": "SMAKalundborg.csv",
            "0306": "SMAOdsherred.csv",
            "0760": "SMARingkøbingSkjern.csv",
            "0773": "SMAMorsø.csv", 
            "0563": "SMAFanø.csv"
        },
        "NOT_AFFECTED": {
            "0530": "SMABillund.csv",
            "0575": "SMAVejen.csv",
            "0630": "SMAVejle.csv",
            "0510": "SMAHaderslev.csv",
            "0580": "SMAAabenraa.csv",
            "0621": "SMAKolding.csv",
            "0540": "SMASønderborg.csv",
            "0607": "SMAFredericia.csv",
            "0461": "SMAOdense.csv",
            "0756": "SMAIkastBrande.csv"
        },
        "StartDate": date(2021, 1, 28),
        "EndDate": date(2022, 1, 28),
    },
    "OTTO": { #Storm
        "BaseDir": "StormOtto",
        "AffectedFolder": "affected",
        "NotAffectedFolder": "notAffected",
        "AFFECTED": {
            "0665": "SOTLemvig.csv",
            "0787": "SOTThisted.csv",
            "0773": "SOTMorsø.csv",
            "0779": "SOTSkive.csv",
            "0849": "SOTJammerbugt.csv",
            "0661": "SOTHolstebro.csv",
            "0851": "SOTAalborg.csv",
            "0820": "SOTVesthimmerland.csv",
            "0706": "SOTSyddjurs.csv",
            "0671": "SOTStruer.csv"
        },
        "NOT_AFFECTED": {
            "0760": "SOTRingkøbingSkjern.csv",
            "0270": "SOTGribskov.csv",
            "0219": "SOTHillerød.csv",
            "0751": "SOTAarhus.csv",
            "0561": "SOTEsbjerg.csv",
            "0540": "SOTSønderborg.csv",
            "0330": "SOTSlagelse.csv",
            "0370": "SOTNæstved.csv",
            "0479": "SOTSvendborg.csv",
            "0482": "SOTLangeland.csv"

        },
        "StartDate": date(2022, 2, 16),
        "EndDate": date(2023, 2, 16),
    },
    "PIA": { #Storm
        "BaseDir": "StormPia",
        "AffectedFolder": "affected",
        "NotAffectedFolder": "notAffected",
        "AFFECTED": {
            "0665": "SPILemvig.csv",
            "0760": "SPIRingkøbingSkjern.csv",
            "0573": "SPIVarde.csv",
            "0561": "SPIEsbjerg.csv",
            "0563": "SPIFanø.csv",
            "0671": "SPIStruer.csv",
            "0787": "SPIThisted.csv",
            "0756": "SPIIkastBrande.csv",
            "0630": "SPIVejle.csv",
            "0661": "SPIHolstebro.csv"
        },
        "NOT_AFFECTED": {
            "0860": "SPIHjørring.csv",
            "0813": "SPIFrederikshavn.csv",
            "0820": "SPIVesthimmerland.csv",
            "0846": "SPIMariagerfjord.csv",
            "0746": "SPISkanderborg.csv",
            "0430": "SPIFaaborgMidtfyn.csv",
            "0316": "SPIHolbæk.csv",
            "0259": "SPIKøge.csv",
            "0390": "SPIVordingborg.csv",
            "0340": "SPISorø.csv"
        },
        "StartDate": date(2022, 12, 20),
        "EndDate": date(2023, 12, 20),
    },
    "ROLF": { #Storm
        "BaseDir": "StormRolf",
        "AffectedFolder": "affected",
        "NotAffectedFolder": "notAffected",
        "AFFECTED": {
            "0787": "SROThisted.csv",
            "0573": "SROVarde.csv",
            "0561": "SROEsbjerg.csv",
            "0563": "SROFanø.csv",
            "0851": "SROAalborg.csv",
            "0849": "SROJammerbugt.csv",
            "0665": "SROLemvig.csv",
            "0773": "SROMorsø.csv",
            "0813": "SROFrederikshavn.csv",
            "0326": "SROKalundborg.csv"
        },
        "NOT_AFFECTED": {
            "0329": "SRORingsted.csv",
            "0376": "SROGuldborgsund.csv",
            "0621": "SROKolding.csv",
            "0756": "SROIkastBrande.csv",
            "0259": "SROKøge.csv",
            "0360": "SROLolland.csv",
            "0580": "SROAabenraa.csv",
            "0510": "SROHaderslev.csv",
            "0575": "SROVejen.csv",
            "0630": "SROVejle.csv"
        },
        "StartDate": date(2023, 2, 22),
        "EndDate": date(2024, 2, 22),
    },
}
